FROM php:8.1-fpm

WORKDIR /var/www/html

RUN apt-get update

RUN apt-get install --quiet -y --no-install-recommends \
    libzip-dev \
    unzip


RUN docker-php-ext-install zip pdo pdo_mysql


RUN pecl install -o -f redis-5.3.3 && \
    docker-php-ext-enable redis

RUN pecl install mongodb && docker-php-ext-enable mongodb

 COPY --from=composer /usr/bin/composer /usr/bin/composer

 RUN groupadd --gid 501 appuser \
   && useradd --uid 501 -g appuser \
   -G www-data,root --shell /bin/bash \
   --create-home appuser

 USER appuser  